export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED';
export const AUTH_LOGIN_SUCCEED = 'AUTH_LOGIN_SUCCEED';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT';
export const AUTH_GET_USER = 'AUTH_GET_USER';
export const AUTH_GET_USER_SUCCEED = 'AUTH_GET_USER_SUCCEED';
export const AUTH_GET_USER_FAILED = 'AUTH_GET_USER_FAILED';
